openedx/openedx-events

docs/decisions/0001-purpose-of-this-repo.rst

Add ADR for purpose of this repo.
None
**Reviewers:**

doc: Add purpose of this repo ADR

---

README.rst

This PR updates the README file according to the project specifications.
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
Just documentation
Just documentation
**Reviewers:**
finished.
**Author concerns:**

docs: update readme with project specifications

---

CHANGELOG.rst
setup.cfg

This PR adds configuration that changes __init__ when calling bumpversion

chore: add bumpversion configuration

---

docs/decisions/0001-purpose-of-this-repo.rst

This PR updates the ADR: Purpose of this repository
Just documentation
Just documentation
**Reviewers:**
finished.
None

docs: update repo purpose

---

CHANGELOG.rst
openedx_events/__init__.py
setup.cfg

Increasing version from 0.6.0 to 0.7.0.  This is to reflect AvroAttrsBridge's addition to the library.
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 

build: incrementing version and updating changelog

---

CHANGELOG.rst
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py

Changes made due to post review: https://github.com/eduNEXT/openedx-events/pull/36#pullrequestreview-852211327

refactor: Name changes to fit standards

---

README.rst

Point README to readthedocs.
**Reviewers:**
finished.~~

docs: point to readthedocs in README

---

CHANGELOG.rst
openedx_events/__init__.py

**Description:** Describe in a couple of sentences what this PR adds
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
**Installation instructions:** List any non-trivial installation 
instructions.
1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 

chore: version bump

---

docs/decisions/0008-signals-with-pii.rst
docs/index.rst

Added an ADR about handling PII information for event bus events.

docs: add ADR for events and pii

---

.github/workflows/upgrade-python-requirements.yml

This PR adds a github action which opens a PR updating python requirements in a weekly manner tagging the hooks-extension-framework team as reviewers.
File taken -& then modified- from:
https://github.com/openedx/DoneXBlock/blob/master/.github/workflows/upgrade-python-requirements.yml
https://github.com/openedx/blockstore/blob/master/.github/workflows/upgrade-python-requirements.yml
**Github issue**
https://github.com/openedx/openedx-events/issues/93
As soon as possible.
**Reviewers:**
finished.

build: add upgrade Python requirements GitHub action

---

openedx_events/content_authoring/signals.py
openedx_events/enterprise/signals.py
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/tooling.py

This PR changes the wording of a few docstrings & fixes some relevant mistakes.
None
ASAP
Just docs updates.
Just docs updates.
**Reviewers:**
finished.
**Author concerns:**
None

docs: minor fixups/re-wording to docstrings

---

.github/workflows/commitlint.yml

This PR adds a commit lit github workflow to -in the long run- improve commit messages quality,
None
ASAP
**Installation instructions:**
Just another GH workflow.
Just another GH workflow.
**Reviewers:**
finished.

build: add linter for commit messages

---

requirements/doc.in
requirements/doc.txt
setup.py
tox.ini

This PR updates command for package generation since, according to the [Python Packaging User Guide](https://packaging.python.org/en/latest/), we should be using twine.
More info: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
None
ASAP
Just a tox update. Check out CI docs section for results.
Just a tox update. Check out CI docs section for results.
**Reviewers:**
finished.

test: update command for pypi friendly package check

---

docs/conf.py
openedx_events/event_bus/avro/custom_serializers.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

This PR upgrades the library requirements to fix issues with the upgrade requirements bot.
ASAP
Just an upgrade.
Just an upgrade.
**Reviewers:**
finished.
I'm not sure if this will fix the bot issue.

chore: upgrade requirements

---

openedx.yaml

Update metadata ahead of the Olive master branches.

build: this repo is not branched for Open edX releases

---

openedx_events/event_bus/avro/tests/test_deserializer.py
openedx_events/event_bus/avro/tests/test_serializer.py
openedx_events/tests/test_tooling.py
openedx_events/tooling.py

This includes a small change to logging to make it easier to test.

fix: Increase unit test coverage (string_schema, format_responses)

---

docs/decisions/0005-external-event-schema-format.rst
docs/decisions/0007-optional-fields.rst
docs/decisions/0009-course-catalog-info-changed-design.rst

Moves ADRs that have already been fully implemented from Provisional to Accepted
**ISSUE:**
https://github.com/edx/edx-arch-experiments/issues/116
**Reviewers:**
finished.

docs: mark implemented ADRs as accepted

---

openedx_events/event_bus/__init__.py

docs: Use real example for `EVENT_BUS_PRODUCER`

---

openedx_events/__init__.py

**Description:** Describe in a couple of sentences what this PR adds
**ISSUE:** Link to GitHub issue
**Dependencies:** dependencies on other outstanding PRs, issues, etc.
**Installation instructions:** List any non-trivial installation
instructions.
1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.
**Reviewers:**
finished.

fix: update version to 4.0.0

---

CHANGELOG.rst

docs: Include new cert signals in changelog

---

openedx_events/__init__.py

**Description:** Bump version to release latest changes
**ISSUE:** Link to GitHub issue
**Dependencies:** dependencies on other outstanding PRs, issues, etc.
**Installation instructions:** List any non-trivial installation
instructions.
1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.
**Reviewers:**
finished.

chore: bump version to 8.9.0

---

MANIFEST.in
setup.py

This PR is a continuation of: https://github.com/openedx/openedx-events/pull/262

fix: setup.py update using script

---

.github/workflows/ci.yml

This PR updates codecov to the latest release which use tokens per repository.

build: update codecov action to latest version with repo-specific tokens

---

CHANGELOG.rst
openedx_events/__init__.py

This PR updates the release docs before v9.10.0 release.

docs: update docs for upcoming release

---

docs/concepts/hooks-extension-framework.rst

fix: typo fix in hooks-extension-framework.rst

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml

This PR addresses the missing changes changes to solve: #383

build: build pypi package using ubuntu 24.04

---

docs/decisions/0001-purpose-of-this-repo.rst

This PR updates the repository purpose ADR as accepted since this solution has been used for a couple of years.

docs: update repo purpose to status accepted

---

docs/reference/index.rst
docs/reference/real-life-use-cases.rst

This PR adds a list of community use cases based on the results of GraphQL queries and GH searches. You can review the result here: https://docsopenedxorg--416.org.readthedocs.build/projects/openedx-events/en/416/reference/real-life-use-cases.html

docs: [FC-0074] add real life use cases based on community adoption

---

.github/PULL_REQUEST_TEMPLATE.md
docs/conf.py
docs/how-tos/use-the-event-bus-to-broadcast-and-consume-events.rst
docs/reference/real-life-use-cases.rst
requirements/base.txt
requirements/dev.txt
requirements/doc.in
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

This PR:
1. Add use case about integrating external services using the event bus, addressing this comment: https://github.com/openedx/openedx-events/pull/426#discussion_r1871957989
2. Add clarification about each event bus configuration field
3. Improve PR template by fixing typo and clarifying review of service integration
4. Take settings source path from configurations instead
You can see it rendered here:
1. https://docsopenedxorg--460.org.readthedocs.build/projects/openedx-events/en/460/reference/real-life-use-cases.html#external-services-integration
2. : https://docsopenedxorg--460.org.readthedocs.build/projects/openedx-events/en/460/how-tos/use-the-event-bus-to-broadcast-and-consume-events.html#step-3-produce-the-event
3. NA
4. …

docs: [FC-0074] address new docs feedback 

---

docs/how-tos/consume-an-event.rst

This PR modified the title codes according to the Open edX documentation style guide and a few style changes.
Describe what this pull request changes, and why. Include implications for people using this change.
Design decisions and their rationales should be documented in the repo (docstring / ADR), per
[OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.
Useful information to include:
- Motivation and context of the implementation
- What's the intended use of this change?
- Use cases and usage examples available
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions. Also, link to any relevant documentation useful for reviewers.
Be sure to check they are publicly …

docs: [FC-0074] Consume-an-event style review

---

docs/how-tos/add-new-event-bus-concrete-implementation.rst

This PR modified the title codes according to the Open edX documentation style guide and a few style changes.
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions. Also, link to any relevant documentation useful for reviewers.
Be sure to check they are publicly readable, or if not, repeat the information here.
Please provide detailed step-by-step instructions for testing this change, including any necessary setup, e.g., additional requirements, plugins, configuration variables, etc, and environment details to ensure the reviewer can test the change.
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
Include anything else that will help reviewers and consumers understand the change.
- Any other …

docs: [FC-0074] add-new-event-bus-concrete-implementation style review

---

docs/how-tos/add-event-bus-support-to-an-event.rst

This PR modified the title codes according to the Open edX documentation style guide and a few style changes.
Describe what this pull request changes, and why. Include implications for people using this change.
Design decisions and their rationales should be documented in the repo (docstring / ADR), per
[OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.
Useful information to include:
- Motivation and context of the implementation
- What's the intended use of this change?
- Use cases and usage examples available
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions. Also, link to any relevant documentation useful for reviewers.
Be sure to check they are publicly …

docs: [FC-0074] add-event-bus-support-to-an-event style review
