openedx_events/signals/auth/v1/__init__.py

**Description:** This changes the provided parameters of the post login signal to include the request.
**Author concerns:**
Still not sure if we need this, we should remove the site parameter and the consider if we need to pass the request or instead get the request with crum.get_current_request in the receivers of the signal.

feat: change login signal to only include user parameter

---

CHANGELOG.rst
manage.py
test_utils/test_settings.py
tox.ini

This PR adds the necessary configuration to run unittesting using django settings. Taken from: https://github.com/eduNEXT/openedx-filters/pull/3
**Reviewers:**
finished.

test: add testing configuration

---

CHANGELOG.rst

This PR fixes the markdown error that prevented publishing the package on pypi

fix: fix pypi rendering error

---

openedx_events/learning/signals.py

This PR adds the first 8 definitions of the Open edX events, they will be used in the Open edX platform.
**JIRA:** Link to JIRA ticket
**Dependencies:**\
Depends on #8 
With the event `STUDENT_REGISTRATION_COMPLETED`:
In your Open edX devstack
1. Go to lms shell `make lms-shell`
2. Install openedx-events specifying the events definition branch:
`pip install git+https://github.com/eduNEXT/openedx-events.git@MJG/events_definition#egg=events_definition` 
3. Change the Open edX platform branch to [MJG/post_register_event](https://github.com/eduNEXT/edx-platform/pull/221)
4. Connect your custom receiver to the signal as follows:
```
from openedx_events.learning.signals import STUDENT_REGISTRATION_COMPLETED
@receiver(STUDENT_REGISTRATION_COMPLETED) …
```

feat: preliminary signal definition

---

tox.ini

This PR adds support for 120 max doc lines. Suggestion taken from: https://github.com/eduNEXT/openedx-events/pull/18#discussion_r675183610

test: remove max-doc-length from tox.ini file due to community recommendation

---

CHANGELOG.rst
openedx_events/data.py
openedx_events/exceptions.py
openedx_events/tests/test_tooling.py
openedx_events/tooling.py
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

This PR adds the tooling needed to create and trigger events in Open edX platform. This PR includes:
- OpenEdxPublicSignal class: used to define events with the relevant metadata and methods to trigger them on the Open edX platform. 
- Custom Exceptions: raised by the tooling when there's an error sending or instantiating events
The overall implementation was discussed by members of the community in this PR: #4 
**JIRA:** 
https://edunext.atlassian.net/browse/PS2021-629?atlOrigin=eyJpIjoiODIwNDA5M2MxZGRlNGQ2NjhjNjJhZWIwNWZiNWNlYjUiLCJwIjoiaiJ9
Option 1: using PR #18 
With the event `STUDENT_REGISTRATION_COMPLETED`:
In your Open edX devstack
1. Go to lms shell `make lms-shell`
2. Install openedx-events specifying the events definition branch: …

feat: add necessary tooling for Open edX events 

---

openedx_events/learning/data.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

This PR adds class definitions for the objects that will be sent by Open edX events, they are based in the library
**JIRA:**
https://edunext.atlassian.net/browse/PS2021-629?atlOrigin=eyJpIjoiODIwNDA5M2MxZGRlNGQ2NjhjNjJhZWIwNWZiNWNlYjUiLCJwIjoiaiJ9
This PR depends on #7 
In your Open edX devstack
1. Go to lms shell `make lms-shell`
2. Install openedx-events specifying the events definition branch:
`pip install git+https://github.com/eduNEXT/openedx-events.git@MJG/event_data#egg=event_data` 
3. Go to the lms Django shell: `python manage.py lms shell`
4. Now, you can import the platform objects and map them to attrs classes. For example, you could do:
```
>>> from common.djangoapps.student.models import CourseEnrollment
>>> from …
```

feat: add data attributes definition for learning subdomain

---

openedx_events/tests/test_tooling.py
openedx_events/tooling.py

This PR fixes the following error:
The implementation was correct when metadata was just a dictionary

fix: remove assignment to metadata object

---

openedx_events/tests/__init__.py
openedx_events/tests/test_tooling.py
openedx_events/tests/utils.py
openedx_events/tooling.py

This PR adds classes and methods that allow developers to enable/disable events during testing. This implementation is a result of [this](https://github.com/edx/edx-platform/pull/28266#discussion_r692455863) discussion
1. `make lms-shell`
2. pip install git+https://github.com/eduNEXT/openedx-events@MJG/isolate_signal_sending#egg=openedx-events==0.5.0_alpha
3. Go to [openedx/core/djangoapps/user_api/tests/test_views.py L31](https://github.com/edx/edx-platform/blob/572965b7427c4c122abc78b04a624ed6a13e9742/openedx/core/djangoapps/user_api/tests/test_views.py#L31) 
4. In `UserAPITestCase` add the mixin `OpenEdxEventsTestCase`
5. Execute tests, for example: `pytest openedx/core/djangoapps/user_authn/views/tests/test_register.py::RegistrationValidation …

test: add signal isolation class and methods

---

CHANGELOG.rst
openedx_events/tests/test_tooling.py
openedx_events/tooling.py

The code block was necessary when we used defaults for event_data and data, but after changing them to positional args is useless.

refactor: remove unnecessary instantiation check

---

CHANGELOG.rst
openedx_events/tests/test_tooling.py
openedx_events/tests/utils.py
openedx_events/tooling.py
openedx_events/utils.py

This PR changes which send method to use when sending an event, so they don't fail during runtime. Instead, they will be allowed to fail in a testing/dev environment.
Test new default:
One of the ways to test the new default besides a production environment is in a test environment where no events are turned on. Meaning, the test class has the mixin `OpenEdxEventsTestMixin` with `ENABLED_OPENEDX_EVENTS = []`. For example: 
https://github.com/edx/edx-platform/blob/master/common/djangoapps/student/tests/test_enrollment.py#L34
1. In a testing environment, connect a handler to one of the Open edX Events available. For example, from a plugin you could do:
```
{
"receiver_func_name": "enrollment_receiver",
"signal_path": …
```

feat: change send_robust to default method

---

CHANGELOG.rst
openedx_events/learning/data.py
openedx_events/learning/signals.py

This PR extract the definition of `COURSE_DISCUSSIONS_CHANGED` event and his `attr` data from `edx-platform` to `openedx-events` library.
1. In studio, modified the content of a course in a unit and publish changes
2. You should see new DiscussionTopicLink objects, one for each general topic and one for each unit.
3. In studio logs you can see `log.info` for "Updating existing discussion topic links for" or "Creating new discussion topic links for"
4. In django admin you can see `DiscussionsConfiguration` in change discussions configuration 
**Support information:**
PRs merge in `openedx/edx-platform`
- https://github.com/openedx/edx-platform/pull/29082
- https://github.com/openedx/edx-platform/pull/28749 …

feat: Discussion event extraction, in openedx-event library

---

CHANGELOG.rst
openedx_events/learning/data.py

In this [PR](https://github.com/openedx/openedx-events/pull/45), a new event was introduced with its data classes, but it was missing two changes
that are being added here.
* Add ordering field to DiscussionTopicContext
* Add more context to class arguments
Follow test instructions in [this](https://github.com/openedx/edx-platform/pull/29930) PR.
finished.

refactor: add missing information to data classes

---

README.rst
docs/decisions/0006-event-schema-serialization-and-evolution.rst

Updates several url references from when this
repo was still part of the eduNEXT org, and not
yet part of the openedx org.

docs: fix eduNEXT to openedx move

---

docs/conf.py
tox.ini

It was previously being set in the tox.ini which was fine when we were building
locally but readthedocs.org does not use it.  Moving the setting into
docs/conf.py means it should work from anywhere.

build: Move where we set the DJANGO_SETTINGS_MODULE.

---

.readthedocs.yml
docs/conf.py
openedx_events/utils.py
tox.ini

**Description:** Fail doc builds on warnings.
1. Run `make docs`
2. Verify that no warnings are displayed and docs build successfully.
**Reviewers:**

build: Fail docs builds on sphinx warnings.

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/learning/data.py

Adds a new `context` field to DiscussionTopicContext that can be used to store
additional context information such as the topics's section and subsection.
This ADR with additional information on this can be found here:
https://github.com/openedx/edx-platform/pull/29928
It also marks the `group_id` attr as optional.
**JIRA:** https://openedx.atlassian.net/browse/TNL-9673
- In the lms and cms containers install this PR using: 
`pip install git+https://github.com/openedx/openedx-events.git@refs/pull/51/head`
Follow instructions from: https://github.com/openedx/edx-platform/pull/30140
**Reviewers:**
finished.

feat: update DiscussionTopicContext to add additional context [BD-38] [TNL-9673]

---

.gitignore
CHANGELOG.rst
docs/decisions/0004-external-event-bus-and-django-signal-events.rst
docs/decisions/0005-external-event-schema-format.rst
docs/how_tos/avro_attrs_bridge.rst
openedx_events/bridge/avro_attrs_bridge.py
openedx_events/bridge/avro_attrs_bridge_extensions.py
openedx_events/bridge/avro_types.py
openedx_events/bridge/tests/test_avro_attrs_bridge.py
openedx_events/bridge/tests/test_utilities.py

The original bridge converted ``attrs`` classes to Avro schemas. This PR updates the bridge class to take an instance of an OpenEdxPublicSignal and create an Avro schema representing its entire init_data (which defines the schema for events this signal expects to emit). This PR also removes any work around schema evolution, which will be left to future work. 
Finally, this PR updates the tests and documentation.
**JIRA:** 
[ARCHBOM-2038](https://openedx.atlassian.net/browse/ARCHBOM-2038)
See https://github.com/edx/edx-arch-experiments/blob/60730a6e78bd4ae6dcaf8c985a696f387b7efa29/edx_arch_experiments/kafka_consumer/tests/test_bridge_use.py for an example of how to test these events with the 
AvroDe/Serializer classes from the confluent_kafka …

Modify avroattrsbridge to work with signal classes instead

---

catalog-info.yml

**Description:** This adds the catalog-info.yml file, which provides structured data around Maintainers for a new tool we're using called Backstage
**Merge deadline:** Needs to go along with the OEP-55 (maintainers)  work that I believe @mariajgrimaldi is going to work on.
**Reviewers:**
finished.
**Author concerns:** None

build: Add structured Maintainers information

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py

**Description:** Removes email from SubscriptionLicenseData attrs object to prevent it from going to Kafka
Also changes the Subscription License Modified event to v0 to make it clear it should not be used in production and might be modified at any time.
In a future world this type of thing would require more thoughts around migration but that will wait until after we have something end-to-end with the bridge.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 

fix: remove email from subscription license event

---

openedx_events/tests/test_tooling.py
openedx_events/tooling.py

I wanted to start relying on the KeyError not-found behavior in another library and realized it wasn't actually documented or tested.

test: Add unit test locking in KeyError when signal not found

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/avro/serializer.py
openedx_events/event_bus/avro/tests/test_serializer.py
openedx_events/event_bus/avro/tests/test_utilities.py

Fixes https://github.com/openedx/openedx-events/issues/82

fix: Handle optional (None) values for custom serializers

---

README.rst

This PR updates the readme file following the OEP-55 recommendations, especially [this](https://raw.githubusercontent.com/openedx/edx-cookiecutters/master/python-template/%7B%7Bcookiecutter.placeholder_repo_name%7D%7D/README.rst) cookie-cutter template. 
This PR resolves #92. 
None
**Merge deadline:**
ASAP
Just documentation.
Just documentation.
**Reviewers:**
finished.
~~**Question**: in the deployment section, should we add that the library works out of the box since maple?~~ already resolved

docs: update readme following oep-55 recommendations

---

.github/workflows/upgrade-python-requirements.yml
CHANGELOG.rst

This PR changes the current requirements bot for a community-supported health file. We're also changing this job in an attempt to fix the current bot errors: https://github.com/openedx/openedx-events/actions/workflows/upgrade-python-requirements.yml
None
**Merge deadline:**
ASAP
None
None
**Reviewers:**
finished.

build: change GitHub to community maintained repository health file

---

.github/workflows/upgrade-python-requirements.yml

This PR adds missing SMTP secrets for the requirements job, which [failed](https://github.com/openedx/openedx-events/actions/runs/3024132560) while setting up the environment. This is a continuation of PR #106 since we missed those secrets there.
**JIRA:** 
None
None
ASAP
None, it's a github action change.
1. Go to actions
2. Select this branch
3. Select upgrade requirements job
4. Run job
You'll pass the setup step, & it will fail while creating the pull request.
**Reviewers:**
finished.
The job fails with 404 while creating the pull request, more info [here](https://github.com/openedx/openedx-events/runs/8275216199?c …

fix: add missing secrets for requirements job

---

.github/workflows/ci.yml

This PR adds coverage step to CI GitHub pipeline.
None
ASAP
None. New GitHub pipeline step.
None. New GitHub pipeline step. Check out the org coverage page for openedx-events: [here](https://app.codecov.io/gh/openedx/openedx-events/pull/111)
**Reviewers:**
finished.
None

ci: add coverage step as part of CI pipeline

---

docs/decisions/0009-course-catalog-info-changed-design.rst
docs/index.rst

**Description:** Adds an ADR explaining the rationale for designing the course-catalog-info-changed event in such a way as to only work when Publisher is enabled.
Since it's just a docs update I didn't update the version
**Reviewers:**
finished.

docs: ADR for course-catalog-info-changed event design

---

.github/workflows/upgrade-python-requirements.yml

We added `$default-branch` to the upgrade workflow
based on the upgrade workflow's template in
our .github repo.
It turns out that `$default-branch` only works in
workflow templates. In actual workflows,
it needs to be expanded to `main` or `master`.
@mariajgrimaldi @sarina

build: expand '$default-branch' in upgrade workflow

---

openedx_events/__init__.py
setup.cfg

This PR bumps the library version references to v0.13.0

Bump version: 0.12.0 → 0.13.0

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py

**Description:** Removes the short_description field from CourseCatalogData since it's not used in systems that have publisher. See 0009-course-catalog-info-changed-design.rst . 
**ISSUE:** https://github.com/openedx/openedx-events/issues/121
**Reviewers:**
finished.

feat: remove unused short_description field on CourseCatalogData

---

CHANGELOG.rst
openedx_events/__init__.py
setup.cfg

According to semver, 0.x versions may have breaking changes at any time, and there's no way to communicate them via the version number until the version is at least 1.0.0. Since this is in active use now, we should bump to 1.0.0.

docs: Bump version to 1.x to acknowledge that this is in use in production

---

CHANGELOG.rst
docs/decisions/0009-course-catalog-info-changed-design.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py

Removes "effort" field in CourseCatalogData. This field is not actually editable in Studio in setups where Publisher is enabled. Also updates the ADR around COURSE_CATALOG_INFO_CHANGED event design to clarify the fields not being copied from the courses API endpoint.
Note that this is in fact a breaking change and will require some work in edx-platform (and possibly discovery) to bring it in. 
Issue: https://github.com/openedx/openedx-events/issues/133
**Reviewers:**
finished.

feat!: remove effort field from CourseCatalogData

---

openedx_events/event_bus/avro/schema.py

ARCHBOM-2013 was migrated and ARCHBOM-2095 was closed as "won't do (for now)".

docs: Clean up EventBus TODO markers

---

docs/decisions/0008-signals-with-pii.rst

Also, clean up formatting.
This relates to https://github.com/openedx/event-bus-kafka/issues/62

docs: Note that PII may also enter logs

---

CHANGELOG.rst
openedx_events/event_bus/__init__.py
openedx_events/event_bus/tests/test_loader.py

Make the event_metadata parameter in the send() method of the EventProducer class required. 
**ISSUE:** https://github.com/openedx/openedx-events/issues/153
**Dependencies:** Don't merge until after https://github.com/openedx/event-bus-kafka/pull/88 is merged
**Reviewers:**
finished.

feat!: make event_metadata parameter required

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/custom_serializers.py
openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/event_bus/avro/tests/test_deserializer.py
openedx_events/event_bus/avro/tests/test_serializer.py

**Description:** Adds events and data classes to allow consumers to react on xblock events like published, deleted and duplicated. 
The idea is to fire these events in [delete_item](https://github.com/openedx/edx-platform/blob/4c0b0f99a0d874c589c4dbf1ea44cdfc84edf7f9/lms/djangoapps/ccx/modulestore.py#L237), [publish_item](https://github.com/openedx/edx-platform/blob/4c0b0f99a0d874c589c4dbf1ea44cdfc84edf7f9/lms/djangoapps/ccx/modulestore.py#L263) and [_duplicate_item](https://github.com/openedx/edx-platform/blob/5bc00b373c879fb2859b44d338f81647210c0909/cms/djangoapps/contentstore/views/item.py#L878) and update skills related to the xblock in [taxonomy-connector](https://github.com/openedx/taxonomy-connector) (part of course-discovery).
**Answer for a question asked in previous similar …

feat: adds events to handle changes in xblocks

---

openedx_events/utils.py

**Description:** This PR modified collections import for use with Python 3.10. Using or importing the ABCs from `collections` instead of from `collections.abc` is deprecated since Python 3.3, and in 3.10 it will stop working
**ISSUE:** https://github.com/openedx/openedx-events/issues/128
**Dependencies:** None
**Merge deadline:** None
**Installation instructions:** None
1. Clone this repo and use the branch
2. Create a viertual environment (use Python 3.8)
3. Run `make requirements`
4. Run `make validate`
5. Repeat steps 2, 3, 4 with python 3.10
**Reviewers:**
finished.
**Author concerns:** None

refactor: use collections.abc import to use with python 3.8 and 3.10

---

CHANGELOG.rst
openedx_events/__init__.py
setup.cfg

This PR updates the openedx-events version for the latest patch release.

docs: bump version for patch release

---

CHANGELOG.rst
openedx_events/data.py
openedx_events/event_bus/tests/test_loader.py
openedx_events/tests/test_tooling.py
openedx_events/tooling.py

* Updated time metadata to include UTC timezone. Original implementation used utcnow(), which could give different results if the time were ever
interpreted to be local time. See https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
* Updated send_event to optionally take a time, which would be used for the metadata. Ideally, this will be explicitly set.
**ISSUE:**
* Implements first part of https://github.com/openedx/openedx-events/issues/162
* edx-platform will require an update to send the db time for the catalog event.
* event-bus-kafka will require passing on the time during event production.  
* Another change is needed in this library for `send_event_in_bus_consumer`, which will require an additional breaking change to EventsMetadata. That will …

feat: updated event signal metadata time

---

CHANGELOG.rst
openedx_events/data.py
openedx_events/event_bus/tests/test_loader.py

You can now create an EventsMetadata instance
without supplying minorversion, and get the
default of 0.
finished.~~

fix: make minorversion actually optional

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/data.py
openedx_events/tests/test_tooling.py
openedx_events/tooling.py

Added send_event_with_custom_metadata. This new version of send_event enables event bus consumers to send the event signal with the same metadata fields that were used when the event was produced.
**ISSUE:**
https://github.com/openedx/openedx-events/issues/162
Only tested via unit tests at this point. I could possibly make other PRs using these changes and pulling in openedx-events from this branch. But, it may be simpler to just release and fix forward if there are any issues, since no one else will be using the new method.
finished.

feat: add send_event_with_custom_metadata

---

openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/tests/test_avro.py

**Description:** This pr adds signals to save/delete certificate configuration for a course.
**ISSUE:** [Link to GitHub issue](https://github.com/openedx/credentials/issues/1765)
**Reviewers:**
finished.

[FC-0004][RG]/edxoldmng 218/Signals to save/delete certificate configuration for a course.

---

openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/tests/utils.py

This will ensure that when new signals are added in new domains, they'll be picked up by the tests. There's still a hardcoded list, but it's just there to ensure there aren't silent regressions.

test: Automatically discover new signals.py files in tests

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/avro/deserializer.py
openedx_events/event_bus/avro/schema.py
openedx_events/event_bus/avro/serializer.py
openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/event_bus/avro/tests/test_deserializer.py
openedx_events/event_bus/avro/tests/test_schema.py
openedx_events/event_bus/avro/types.py
openedx_events/learning/data.py
openedx_events/learning/signals.py

Adds data class and event to send skill verification data for an XBlock.
Updates avro serialization & de serialization just enough to support array types.
**Description:** The idea is that users will verify the tags/skills associated to an XBlock. We want to send this data via openedx-event signals to course-discovery and update the relevant tables.
**JIRA:** `Private-ref`: [BB-6885](https://tasks.opencraft.com/browse/BB-6885)
**Dependencies:** https://github.com/openedx/openedx-events/pull/143 
Original MR: https://github.com/open-craft/openedx-events/pull/1
finished.
**Author concerns:** Only support for array type is added as it is required for this event.

feat: xblock skill verification event

---

.github/workflows/ci.yml
requirements/ci.in
requirements/ci.txt
requirements/dev.txt

This fixes `make requirements`. Upgrading the GHA while I'm at it.
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259

fix: Remove yanked codecov package to unbreak dev; upgrade GH action

---

.github/CODEOWNERS

**Description:** This PR adds a .github/CODEOWNERS file to bring the repo up to day with the maintainers program
**Dependencies:** None
**Merge deadline:** None, but hopefully soon
**Installation instructions:** None, it's all done by github
1. Open a PR or an issue in this Repo
2. The team @openedx/hooks-extension-framework should be tagged automatically
**Reviewers:**
finished.
**Author concerns:** Given it is a simple PR that only changes the github process lightly I have no concerns

Adding a codeowners file as part of the maintainers protocol

---

CHANGELOG.rst
manage.py
openedx_events/__init__.py
openedx_events/apps.py
openedx_events/event_bus/__init__.py
openedx_events/event_bus/tests/test_loader.py
openedx_events/management/__init__.py
openedx_events/management/commands/__init__.py
openedx_events/management/commands/consume_events.py
openedx_events/tests/test_consume_events_command.py

**Description:** This defines an API for IDAs to use when consuming events that allows the choice of Event Bus implementation to be configured rather than written in code. 
It also includes a management command to start a worker and allows to pass in extra arguments for the underlying implementation of event bus.
**ISSUE:** #147 
**Dependencies:** None
Please refer to https://github.com/openedx/event-bus-redis/pull/13 for testing instructions.
**Reviewers:**
finished.
**Author concerns:** The management command implement in [event-bus-kafka takes in an argument](https://github.com/openedx/event-bus-kafka/blob/3f0804234449bd1393198896db104f1f93743b7b/edx_event_bus_kafka/internal/c …

feat: configurable loading of event bus consumer

---

docs/decisions/0010-multiple-event-types-per-topic.rst
docs/decisions/index.rst

Adds an ADR explaining that all implementations of the event bus must support multiple event types per topic.
**ISSUE:** https://github.com/openedx/openedx-events/issues/78
**Reviewers:**
- [N/A] Version bumped
- [N/A] Changelog record added
- [N/A] Create a tag
- [N/A] Check new version is pushed to PyPI after tag-triggered build is
finished.

docs: ADR for multiple event types per topic

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/__init__.py
openedx_events/management/commands/consume_events.py

Removes the deprecated and unused 'signal' argument from consume_events and the underlying consumer abstract class.
**ISSUE:** https://github.com/openedx/openedx-events/issues/218
(private link) https://github.com/edx/edx-internal/pull/8382
**Reviewers:**
finished.

feat!: remove signal argument from consumer

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/learning/signals.py

fix: use correct subdomain in event_type of XBLOCK_SKILL_VERIFIED

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+course+catalog_info+changed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+duplicated+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+published+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+skill+verified+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+auth+session+login+completed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+certificate+changed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+certificate+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+certificate+revoked+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+cohort_membership+changed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+course+enrollment+changed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+course+enrollment+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+course+persistent_grade_summary+changed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+course+unenrollment+completed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+student+registration+completed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+xblock+skill+verified+v1_schema.avsc
openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/event_bus/avro/tests/test_utilities.py
openedx_events/management/commands/generate_avro_schemas.py
openedx_events/tests/test_generate_avro_schemas.py
openedx_events/tooling.py

Add unit tests to confirm that any schema updates are backward and forward compatible with stored versions. Also adds a management command to generate and store the current Avro schema for each signal.
Manual testing:
Test 1: Add required field "thing" to CourseEnrollmentData
`FAILED openedx_events/event_bus/avro/tests/test_avro.py::TestAvro::test_evolution_is_backward_compatible - fastavro._read_common.SchemaResolutionError: No default value for thing`
Test 2: Remove required field "creation_date" from CourseEnrollmentData
`FAILED openedx_events/event_bus/avro/tests/test_avro.py::TestAvro::test_evolution_is_forward_compatible - fastavro._read_common.SchemaResolutionError: No default value for creation_date`
Test 3: Change type of user_data from UserData to str in …

feat: add unit tests around schema evolution

---

docs/decisions/0011-depending-on-multiple-event-bus-implementations.rst
docs/decisions/index.rst

Issue: https://github.com/openedx/openedx-events/issues/209

docs: Add ADR for depending on multiple event bus implementations

---

README.rst

Inspired by [this PR](https://github.com/openedx/openedx-filters/pull/94/) opened in the openedx-filters repository. This PR relies on this https://github.com/openedx/wg-security/issues/15 to update the security email contact.

fix: update security contact email for the correct new one

---

docs/decisions/0012-producing-to-event-bus-via-settings.rst
docs/decisions/index.rst

**Description:** ADR for enabling producing to event bus via settings
**ISSUE:** https://github.com/openedx/openedx-events/issues/210
finished.

docs: adr for enabling producing to event bus via settings

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/custom_serializers.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+updated+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+course+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+library_block+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+library_block+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+library_block+updated+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+xblock+updated+v1_schema.avsc
openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/event_bus/avro/tests/test_deserializer.py
openedx_events/event_bus/avro/tests/test_serializer.py

**Description:** Create the following `OpenEdxPublicSignal` events triggered by content creation and editing.
* XBLOCK_CREATED and XBLOCK_UPDATED
* COURSE_CREATED 
* CONTENT_LIBRARY_CREATED, CONTENT_LIBRARY_UPDATED and CONTENT_LIBRARY_DELETED
* LIBRARY_BLOCK_CREATED, LIBRARY_BLOCK_UPDATED and LIBRARY_BLOCK_DELETED
These events will be used in the auto-tagging feature and is part of [System Defined Taxonomies](https://github.com/openedx/modular-learning/issues/61) feature.
More information: https://github.com/openedx/edx-platform/pull/32599
**Reviewers:**
finished.

feat: add new content authoring event signals

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+program+certificate+awarded+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+program+certificate+revoked+v1_schema.avsc
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/management/commands/generate_avro_schemas.py

Internal 2U ticket: APER-2625
This PR adds new `OpenEdxPublicSignal` events triggered by program certificate generation and revocation.
- Adds a `PROGRAM_CERTIFICATE_AWARDED` event
- Adds a `PROGRAM_CERTIFICATE_REVOKED` event
- Adds new `ProgramCertificateData` and `ProgramData` data classes to support the new events
**ISSUE:** https://github.com/openedx/openedx-events/issues/250
**Reviewers:**
finished.
**Author concerns:** None at this time.

feat: add new program certificate events

---

.readthedocs.yml
CHANGELOG.rst
docs/how-tos/adding-events-to-event-bus.rst
openedx_events/__init__.py
openedx_events/apps.py
openedx_events/exceptions.py
openedx_events/tests/test_producer_config.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
test_utils/test_settings.py

**Description:** Implements ADR merged in #224 .
**ISSUE:** #210 
* Clone this repository and checkout this PR.
* Update stub implementation of producer based on below patch
```diff
diff --git a/openedx_events/event_bus/__init__.py b/openedx_events/event_bus/__init__.py
index 582effe..a4bf597 100644
--- a/openedx_events/event_bus/__init__.py
+++ b/openedx_events/event_bus/__init__.py
@@ -100,6 +100,11 @@ class NoEventBusProducer(EventBusProducer):
event_metadata: EventsMetadata,
) -> None:
"""Do nothing."""
+        print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
+        print(f"""NoEventBusProducer#send signal: {signal}""")
+        print(f"""NoEventBusProducer#send topic: {topic}""")
+ …
```

feat: enable producing to event bus via settings

---

CHANGELOG.rst
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/tooling.py

**Description:** This PR creates signals for events related to forum threads and comments
Extracted from: https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#edx-forum-thread-created
This PR is the base for https://github.com/openedx/edx-platform/pull/33374

feat: create event for discussion events

---

README.rst

docs: Replace getting-started instructions with link

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/tooling.py

**Description:** This PR adds the `COURSE_NOTIFICATION_REQUESTED` event, that will be emitted whenever there is a request for a notification to be sent to all learners within a course.
The event will be emitted whenever there is a request for a notification to be sent out to a course-wide audience. The event has the `course_key` param identifying the course, and also provides the `audience_filter` param to specify subset of users within a course that the notification should be sent out to. Example of scenarios where this event could be used:
- Send out course updates to all verified learners,
- New Discussion post created in forums for course to be sent to all enrolled learner/ cohorted learners etc.
The event also contains fields like `app_name`, `notification_type`, `content_context` …

feat: add event for course wide notification request

---

docs/conf.py
requirements/constraints.txt
requirements/doc.txt

This PR removes the existing `sphinx-book-theme` to use the latest release. Here's the comment we realized we need to utilize the constraint: https://github.com/openedx/openedx-events/pull/169#discussion_r1073980224
Also, we updated the theme configurations for the latest suggested on the open edx docs: https://docs.openedx.org/en/latest/developers/how-tos/add-sphinx-docs-to-a-repo.html.

build: remove sphinx-book-theme constraint to use latest release

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/data.py
openedx_events/tests/test_data.py

**Description:** Use a new EVENTS_SERVICE_NAME setting to determine the source in EventsMetadata. Defaults to the old SERVICE_VARIANT setting if not set. SERVICE_VARIANT is usually only set on lms or cms, and has other uses, so it makes sense to have a new variable that all services can use for the events.
I didn't talk about how the EVENTS_SERVICE_NAME will be used to set the client id because that is Kafka specific.
pip install -e openedx-events
set EVENTS_SERVICE_NAME in your service settings
fire an event
check that the event source is openedx/<EVENTS_SERVICE_NAME>/web
**Reviewers:**
finished. …

feat: use new setting to set ce_source

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+user+course_access_role+added+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+learning+user+course_access_role+removed+v1_schema.avsc
openedx_events/learning/data.py
openedx_events/learning/signals.py

**Description:** Creates new data class and events for publishing information about the creation or removal of an LMS [CourseAccessRole](https://github.com/openedx/edx-platform/blob/96b360a1ee9c756b6bd1032dc282bdb24d3f152c/common/djangoapps/student/models/user.py#L1044). We are not planning to account for the [roles and permissions changes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3824648277/RBAC+Tech+Spec) at this point, events would be based on how roles currently work.
This will be consumed by [edx-exams](https://github.com/edx/edx-exams) to sync access to instructor tools and actions on the API.
**Author concerns:** These events will be used instead those added by https://github.com/openedx/openedx-events/pull/267. I plan to remove those in a separate PR since there is no …

feat: add courseaccessrole events

---

CHANGELOG.rst
docs/how-tos/add-new-event-bus-concrete-implementation.rst
docs/how-tos/index.rst
openedx_events/__init__.py
openedx_events/tooling.py
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Description:** Adds utility function to reset application state which can be used by event bus implementation to reset request/db_connection before processing events.
**ISSUE:** https://github.com/openedx/event-bus-redis/issues/49
**Related:** 
* https://github.com/openedx/openedx-events/issues/235
* https://github.com/openedx/event-bus-kafka/pull/201
**Reviewers:**
finished.

feat: utility to reset application state before processing event

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/apps.py
openedx_events/tests/test_producer_config.py
openedx_events/tests/test_tooling.py
openedx_events/tooling.py

**Description:** This PR adds a new argument `from_event_bus` to the `send_event` method (and related ones) that allows marking a Django signal as already processed from the event bus and avoids infinite emission of the same signal if such signal is consumed in the same runtime.
The following code block must be used on the consumer to avoid processing the signal in the same process that emitted the signal:
```python
from openedx_events.tooling import SIGNAL_PROCESSED_FROM_EVENT_BUS
...
def my_signal(...):
if not kwargs.get(SIGNAL_PROCESSED_FROM_EVENT_BUS, False):
logger.info("Event received from a non-event bus backend, skipping...")
return
```
This has been tested with the `event-bus-redis` without any changes as the behavior of calling `send_event_with_custom_metadata` is to enable the …

fix: avoid infinite recursion of openedx-event

---

Makefile
docs/conf.py
docs/reference/events.rst
docs/reference/index.rst
openedx_events/analytics/signals.py
openedx_events/content_authoring/signals.py
openedx_events/learning/signals.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
tox.ini

**Description:** Adds automatic documentation of annotated events for discoverability and ease of configuration. This is in draft until dependencies merge and release, so I can update requirements to the official version, I'll be adding event_key_fields for the rest of the events while that is in review. Generated docs look like this:
**Dependencies:** https://github.com/openedx/code-annotations/pull/98
**Installation instructions:** List any non-trivial installation
instructions.
1. Requirements are updated to use the branch of code-annotations necessary to run this so pulling this branch and running `make requirements` should suffice
2. Run `make docs`
3. Sphinx should run and pop open the generated docs in your browser. Navigate to reference -> events to see …

feat: Add autodoc for event annotations

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content+object+tags+changed+v1_schema.avsc

This signal is emitted when tags on a content object have changed.
**Description:** This PR adds a new `CONTENT_OBJECT_TAGGED` signal, which is emitted when a content object's tags have changed.
**ISSUE:** https://github.com/openedx/modular-learning/issues/197
- Needed for edx-platform: https://github.com/open-craft/edx-platform/pull/647
Follow instructions mentioned in https://github.com/open-craft/edx-platform/pull/647
**Reviewers:**
finished.
---
Private-ref: [FAL-3691](https://tasks.opencraft.com/browse/FAL-3691)

[FC-0040] feat: Add `CONTENT_OBJECT_TAGS_CHANGED` signal

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/enterprise/__init__.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy+redeemed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy+redemption-reversed+v1_schema.avsc

**Description:** This PR adds OEP-49 data and signals for learner enrollment fee subsidies provided by enterprises. 
**Issue**: Enterprises provide subsidies to their learners for enrollment. These subsidies are managed via enterprise related repositories such as [enterprise-access](https://github.com/openedx/enterprise-access), [enterprise-subsidy](https://github.com/openedx/enterprise-subsidy), [openedx-ledger](https://github.com/openedx/openedx-ledger). The subsidy redemption and reversal events would be produced/consumed in these repositories for enterprise budget adjustments.
**Reference Usage**
https://github.com/openedx/enterprise-subsidy/pull/227
https://github.com/openedx/enterprise-access/pull/434
**Reviewers:**
finished.

feat: Added enterprise subsidy events. OEP-49

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/learning/data.py

This PR updates the `ORASubmissionData` class to send the same data as the [legacy analytics event](https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/apis/submissions/submissions_actions.py#L162-L171). This will facilitate the transition from one event to another if necessary.
> [!NOTE]
> As this is an event that has not been used yet, there will be no problem in adding these new fields.
The new class attributes are:
- `id` -> `uuid` (Renamed to maintain consistency with the legacy event)
- `anonymous_user_id`
- `location`
- `attempt_number`
- `created_at`
- `submitted_at`
- `answer` (`ORASubmissionAnswer`)
- `parts`
- `file_keys`
- `file_descriptions`
- `file_names`
- `file_sizes`
- `file_urls`
The new fields that are not in the legacy event are:
- …

refactor: update ora submission data

---

.gitignore
CHANGELOG.rst
Makefile
openedx_events/__init__.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py
openedx_events/event_bus/avro/custom_serializers.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy_ledger_transaction+committed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy_ledger_transaction+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy_ledger_transaction+failed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+subsidy_ledger_transaction+reversed+v1_schema.avsc
openedx_events/event_bus/avro/tests/test_avro.py
openedx_events/event_bus/avro/tests/test_custom_serializers.py

* Added new enterprise signals `LEDGER_TRANSACTION_CREATED`, `LEDGER_TRANSACTION_COMMITTED`, `LEDGER_TRANSACTION_FAILED`, and `LEDGER_TRANSACTION_REVERSED`.
* Added a `UuidAvroSerializer` to serialize uuid fields.
* Added `isort` make target.
The best doc to start with is probably this: https://github.com/openedx/enterprise-access/blob/main/docs/decisions/0004-add-access-policy-functionality.rst#context
A Ledger is a model defined in the openedx-ledger repo, it's a core model used in the context of edX Enterprise. https://github.com/openedx/openedx-ledger/blob/main/docs/decisions/0002-ledger-balance-enforcement.rst
It's installed only into enterprise-subsidy AFAIK: https://github.com/openedx/enterprise-subsidy/tree/main/docs/decisions
I don't believe ledgers (or enterprise-subsidy,access) …

feat: new enterprise transaction data/signals

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+learner_credit_course_enrollment+revoked+v1_schema.avsc

feat: Add enterprise signal for learner credit fulfillment revokation

---

.github/workflows/ci.yml
setup.py
tox.ini

Upgrade stack versions from CI matrix so it handles the project's latest supported versions. Also, this solves errors we've been having while upgrading Python requirements since requirements are now updated using Python3.11 exclusively: https://github.com/openedx/openedx-events/pull/391

ci: upgrade os and python-version from CI matrix

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml

According to the discussion https://github.com/openedx/platform-roadmap/issues/377, ubuntu-latest should be used instead.

fix: use ubuntu latest according discussion openedx/platform-roadmap#377

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/enterprise/data.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+learner_credit_course_enrollment+revoked+v1_schema.avsc

This should hopefully fix the error we are currently seeing when attempting to serialize real-life LC fulfillments outside of unit test environments.  The error is exactly described in this ticket for a different event experiencing the same issue:
https://github.com/edx/edx-arch-experiments/issues/788
Basically, certain fields are passed into the serializer as None because the actual value in the database is NULL, but the serializer field default is not explicitly set to None which triggers a code path that doesn't tolerate being passed None:
https://github.com/openedx/openedx-events/blob/3170416c157df480b3d9f9f276ab7cf7b9d5e68d/openedx_events/event_bus/avro/serializer.py#L34-L44
ENT-9213

fix: make nullable django fields also Noneable in event data

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+updated+v1_schema.avsc

This is required to handle the signal asynchronously whenever the sender does not care about the handler execution completion.
For example, whenever multiple collections are updated due to a component being added or removed, we do not want to wait for all collection update handlers to complete.
* https://github.com/openedx/edx-platform/pull/35600
* https://github.com/openedx/openedx-learning/pull/238
* https://github.com/openedx/frontend-app-authoring/pull/1373
**Merge deadline:** ASAP
* See https://github.com/openedx/frontend-app-authoring/pull/1373 for test instructions.
finished.

refactor: add lazy field to LibraryCollectionData

---

docs/decisions/0004-external-event-bus-and-django-signal-events.rst
docs/decisions/0006-event-schema-serialization-and-evolution.rst
docs/decisions/0008-signals-with-pii.rst
docs/decisions/0013-special-exam-submission-and-review-events.rst

This PR updates ADRs statuses from non-accepted status to accepted, assuming the decisions were already implemented.

docs: change ADRs status over a year old to accepted

---

docs/how-tos/adding-events-to-event-bus.rst

**Description:** Updates how-doc to reflect changes from [ADR: 114](https://github.com/open-craft/openedx-events/blob/6f04b4b0d7f0d2c800ec5044e98e708a52c447b8/docs/decisions/0014-new-event-bus-producer-config.rst#L58)
**ISSUE:** N/A
**Dependencies:** None
**Reviewers:**
finished.

docs: update adding events how-to to use new config style

---

docs/how-tos/creating-new-events.rst
docs/how-tos/using-events.rst
docs/quickstarts/use-events-to-call-webhook.rst
docs/reference/glossary.rst
docs/reference/index.rst

This PR:
1. Creates a glossary document for Open edX Events terminology in the reference section. 
2. Uses sphinx utilities to implement a glossary.
3. References glossary throughout all documents when needed.

docs:  [FC-0074] add glossary for openedx-events ecosystem

---

docs/how-tos/using-events.rst

Notes that the custom Django plugin config for signal receivers is no longer recommended.
See:
- https://github.com/openedx/openedx-events/issues/421

docs: update signal receiver how-to

---

docs/concepts/index.rst
docs/conf.py
docs/index.rst
docs/reference/real-life-use-cases.rst

This PR references the main framework documentation in an effort to implement DRY docs.

docs: [FC-0074] reference main hooks docs

---

docs/concepts/openedx-events.rst

This PR:
* Add quote block to Django signals definition from Django docs
* Reference list of use cases in how are events used
* Use "send events internally" instead of within the same app process to improve readability

docs: [FC-0074] improve format and wording in concepts docs

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a new template for Pull Requests with:
1. Specific merge checklist requirements to the repository
2. Easier and more readable format
3. Updated post merge checklist 
Based on: 
https://github.com/openedx/edx-platform/blob/master/.github/pull_request_template.md
https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-python-library/%7B%7Bcookiecutter.library_name%7D%7D/.github/PULL_REQUEST_TEMPLATE.md

docs: [FC-0074] update PR template to reflect latest requirements for repo

---

openedx_events/content_authoring/signals.py
openedx_events/learning/signals.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

Use `.. event_warning` annotation to indicate a critical characteristic of an event. As for now, these warnings have been used to warn users about missing event bus capabilities.
1. Create a venv 
2. Install this version of openedx-events which uses `.. event_warning` instead of a `Warning: ` label.
3. Generate docs for openedx-events by running: `make docs`
Here's the expected output:
This PR depends on https://github.com/openedx/code-annotations/pull/136

docs: [FC-0074] replace warning text with event_warning annotation

---

docs/how-tos/creating-new-events.rst
docs/reference/in-line-code-annotations-for-an-event.rst
docs/reference/index.rst

To improve visibility, this PR moves the in-line code annotation docs for events from a how-to to the reference category. 
This comment addresses this comment: https://github.com/openedx/code-annotations/pull/136#discussion_r1880131463. Once we merge it and make it available, we should reference this new document here https://github.com/openedx/code-annotations/blob/master/code_annotations/contrib/config/openedx_events_annotations.yaml#L9.
You can see the docs when generated here: https://docsopenedxorg--432.org.readthedocs.build/projects/openedx-events/en/432/reference/in-line-code-annotations-for-an-event.html
None
NA
finished.

docs: [FC-0074] add documentation for in-line code annotations

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/learning/signals.py
openedx_events/tooling.py

This PR fixes the forum IDs so:
1. They match each event definition. 
2. They're unique.
This change shouldn't be considered a breaking change since these events are not being sent to the event bus yet, so the `event_type` is not actively used by consumers.
finished.

fix: use correct event type for forum events

---

docs/how-tos/adding-event-bus-support-to-an-event.rst
docs/how-tos/index.rst
docs/how-tos/using-the-event-bus.rst
docs/reference/glossary.rst

This PR adds a how-to guide for implementing an event with event bus support. It details the requirements for sending and receiving events through the event bus and how to ensure compatibility.

docs: [FC-0074] add how-to add event bus support to an Open edX Event

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/analytics/signals.py
openedx_events/content_authoring/signals.py
openedx_events/enterprise/signals.py
openedx_events/learning/signals.py
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt

This PR adds a new code annotation for events indicating where they are being triggered from, including the repository and source file. When rendered in the docs, a link redirects to a GH search with the source file and the event name. 
Events without a triggering field are not being used in any service or are candidates for deprecation: https://github.com/openedx/openedx-events/issues/445
This PR addresses a concern raised by this PR removing hooks docs from edx-platform: https://github.com/openedx/edx-platform/pull/35921#issue-2690350343, where the table referencing where each event was triggered from was dropped.
This PR depends on: https://github.com/openedx/code-annotations/pull/143
You can review the changes here: https://docsopenedxorg--443.org.readthedocs.build/projects/openedx-eve …

feat: [FC-0074] add event trigger information in code annotations

---

docs/concepts/openedx-events.rst
docs/conf.py
docs/how-tos/create-a-new-event.rst
docs/reference/events-data.rst
docs/reference/events-tooling.rst
docs/reference/index.rst
openedx_events/analytics/data.py
openedx_events/analytics/signals.py
openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/data.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py
openedx_events/event_bus/avro/deserializer.py
openedx_events/event_bus/avro/schema.py
openedx_events/event_bus/avro/serializer.py
openedx_events/exceptions.py
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/tooling.py
openedx_events/utils.py

This PR includes tooling and data inline docstrings as part of the documentation to reference when creating a new event. This PR also includes the [napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) sphinx extension to make them more readable in RST formats.
You can see the docs rendered here: 
https://docsopenedxorg--450.org.readthedocs.build/projects/openedx-events/en/450/reference/events-tooling.html
https://docsopenedxorg--450.org.readthedocs.build/projects/openedx-events/en/450/reference/events-data.html
None
finished.

docs: [FC-0074] include tooling and data attributes in references

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+course+import+completed+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+course+post+import+v1_schema.avsc

Adds `COURSE_IMPORT_COMPLETED` signal that is triggered once a course import is completed.
* Related PR: https://github.com/openedx/edx-platform/pull/36111
See https://github.com/openedx/edx-platform/pull/36111
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
Include anything else that will help reviewers and consumers understand the change.
- Any other PRs or issues that should be linked here? Any related PRs?
- Any special concerns or limitations? For example: deprecations, security, or anything you think should be noted.
finished.

feat: add new signal to indicate new course import

---

CHANGELOG.rst
docs/common_refs.rst
docs/concepts/event-bus.rst
docs/concepts/openedx-events.rst
docs/conf.py
docs/how-tos/add-event-bus-support-to-an-event.rst
docs/how-tos/consume-an-event.rst
docs/how-tos/create-a-new-event.rst
docs/how-tos/use-the-event-bus-to-broadcast-and-consume-events.rst
docs/how-tos/use-the-event-bus.rst
docs/quickstarts/use-events-to-call-webhook.rst
docs/reference/architecture-subdomains.rst
docs/reference/real-life-use-cases.rst
openedx_events/__init__.py

This PR adds the [linkcode Sphinx extension](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) to include the source code in the classes, functions, and methods in the documentation.
This PR also adds a missing configuration (`openedxevents_repo_url`) for the code annotation extension. Currently, the links to the source code for all events are broken.
You can check the updated documentation in the checks of this PR.
- Any other PRs or issues that should be linked here? Any related PRs?
- Any special concerns or limitations? For example: deprecations, security, or anything you think should be noted.
finished.

docs: add link code extension

---

docs/concepts/openedx-events.rst
openedx_events/analytics/data.py

We migrated the django-utils docs to docs.openedx.org so update the URLs

docs: update edx.rtd links to docs.openedx.org

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/event_bus/__init__.py
openedx_events/event_bus/tests/test_loader.py

It's misleading to have the management command exit immediately with exit code 0 when the config is missing. It's also a little harder than it should be to debug this scenario because at most you get a warning log message (which is easy to miss). A stack trace and error exit should be clearer.
None
finished.

feat: Raise exception when consume_indefinitely called without config

---

README.rst

This PR fixes the Python CI status badge in the README. The badge was generated in **Actions > Python CI > [•••] > Create status badge**
None
finished.

chore: fix python ci status badge

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/data.py
openedx_events/event_bus/avro/custom_serializers.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+collection+updated+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+container+created+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+container+deleted+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+container+updated+v1_schema.avsc
openedx_events/event_bus/avro/tests/test_avro.py

Refactors the LibraryCollectionData and LibraryContainerData structures to use LibraryCollectionLocator and LibraryContainerLocator keys, respectively, instead of passing `library_key` + string key representation.
We also remove the `library_key` from these data structures -- the library_key can be inferred from the opaque key, so it is redundant to pass them separately.
This refactoring seems reasonable to do without going through deprecation, given the minimal use of these data structures.
cf https://github.com/openedx/openedx-events/pull/479#discussion_r1998824771
Blocks: https://github.com/openedx/edx-platform/pull/36476
Private-ref: [FAL-4120](https://tasks.opencraft.com/browse/FAL-4120)
Code review + CI should be sufficient to verify this change.
ASAP -- would like to get this in …

refactor!: use LibraryCollectionLocator and LibraryContainerLocator in event data structures [FC-0083]

---

CHANGELOG.rst
docs/decisions/0017-event-signal-for-external-grader-score-submission.rst
docs/decisions/index.rst
openedx_events/__init__.py
openedx_events/learning/data.py
openedx_events/learning/signals.py
openedx_events/tooling.py

This PR introduces the foundation for an event-based external grader score submission system. It establishes the core components needed to transition from the HTTP-based XQueue callback architecture to an event-driven approach for updating XBlocks with scoring data.
Key components added:
- `ExternalGraderScoreData` class in `data.py` that encapsulates all necessary score information
- `EXTERNAL_GRADER_SCORE_SUBMITTED` signal in `signals.py` to broadcast scoring events
This implementation provides a standardized way for the edx-submissions service to notify the LMS when an external grader has processed a submission. The event-driven approach offers several advantages over the current HTTP callback system:
- Decoupling of services for better reliability
- Improved scalability through …

FC-73 Add EXTERNAL_GRADER_SCORE_SUBMITTED signal to broadcast scoring events ( Feature: Add external grader score data model and signal))

---

CHANGELOG.rst
openedx_events/content_authoring/data.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+content_library+container+published+v1_schema.avsc
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+library_block+published+v1_schema.avsc

In order to solve [some bugs with our "publish all" functionality](https://github.com/openedx/frontend-app-authoring/issues/1871), I found it would be extremely helpful to differentiate `PUBLISHED` events from other library authoring events like `CREATED`, `UPDATED`, and `DELETED` which all refer to changes to draft blocks/containers, not published.
This PR does several things:
* Creates new `LIBRARY_BLOCK_PUBLISHED` and `LIBRARY_CONTAINER_PUBLISHED` events which indicate any time that the _published_ version of a library item has been modified, including if it is deleted. The existing events like `LIBRARY_BLOCK_UPDATED` are clarified to refer strictly to changes in the draft version, which is normal for the authoring environment.
* Clarifies the docstring on several events
* Deprecates …

feat: add LIBRARY_BLOCK_PUBLISHED, LIBRARY_CONTAINER_PUBLISHED events

---

docs/concepts/event-bus.rst
docs/concepts/index.rst
docs/concepts/openedx-events.rst
docs/decisions/0002-events-naming-and-versioning.rst
docs/decisions/0003-events-payload.rst
docs/decisions/0004-external-event-bus-and-django-signal-events.rst
docs/decisions/0005-external-event-schema-format.rst
docs/decisions/0006-event-schema-serialization-and-evolution.rst
docs/decisions/0007-optional-fields.rst
docs/decisions/0010-multiple-event-types-per-topic.rst
docs/decisions/0012-producing-to-event-bus-via-settings.rst
docs/decisions/0016-event-design-practices.rst
docs/decisions/index.rst
docs/how-tos/add-event-bus-support-to-an-event.rst
docs/how-tos/add-new-event-bus-concrete-implementation.rst
docs/how-tos/consume-an-event.rst
docs/how-tos/create-a-new-event.rst
docs/how-tos/use-the-event-bus-to-broadcast-and-consume-events.rst
docs/index.rst
docs/reference/architecture-subdomains.rst
docs/reference/event-bus-configurations.rst
docs/reference/events-data.rst
docs/reference/events-tooling.rst
docs/reference/events.rst
docs/reference/glossary.rst
docs/reference/in-line-code-annotations-for-an-event.rst
docs/reference/naming-suggestions.rst
docs/reference/real-life-use-cases.rst

Usage of `:doc:` is an antipattern. It is fragile and prone to breaking cross references when docs are moved or renamed.
Adding in `.. _reference:` syntax to files and headings means cross-references can instead be made with the `:ref:` directive, which will (presuming the references themselves are not deleted or renamed) be more robust to docs refactorings.

chore: Add references to docs to make relative, not direct, references

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/enterprise/data.py
openedx_events/enterprise/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+enterprise+enterprise_group+deleted+v1_schema.avsc

- Have event bus running locally. Not set up? Easiest to have me screen share.
- If you have the event bus up, `pip install -e` this into a repo where it can be used and where event bus is configured correctly, and then run this: (if the repo is lms, change command to run `python2 manage.py lms produce_event ...` instead)
- `python3 manage.py produce_event --signal openedx_events.enterprise.signals.ENTERPRISE_GROUP_DELETED \
--topic enterprise-core --key-field enterprise_group.uuid \
--data '{"enterprise_group": { "uuid": "d509a63b-eb11-4dc8-8b84-4688c7335110" }}'`
- Verify that message in event bus is created.
If a budget Group is manually deleted (e.g. through django admin), but the PolicyGroupAssociation is not, we end up in a weird state where the budget is looking for a group that …

feat: add enterprise group deletion event

---

CHANGELOG.rst
openedx_events/__init__.py
openedx_events/content_authoring/signals.py
openedx_events/event_bus/avro/tests/schemas/org+openedx+content_authoring+course+rerun+completed+v1_schema.avsc

Adds `COURSE_RERUN_COMPLETED` signal which is similar to `COURSE_IMPORT_COMPLETED` signal. It is triggered after a course is re-run, allowing us to run some post re-run processes.
The current use of this is to run indexing for search and creation of upstream links for components imported from libraries v2.
* https://github.com/openedx/frontend-app-authoring/issues/2361
* `Private-ref`: https://tasks.opencraft.com/browse/FAL-4245
* https://github.com/openedx/edx-platform/pull/37237
See https://github.com/openedx/edx-platform/pull/37124
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
finished.

feat: add signal that is triggered after a course is re-run
